# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/111wb5RM_JodZpcUvWam11zxciZ9hbObn
"""

mapa = []

for i in range(8):
    fila = []
    for j in range(8):
        if j == 0:
            fila.append("V")
        else:
            fila.append("L")
    mapa.append(fila)

mapa[0][0] = "E"
mapa[7][0] = "S"


placas = []
ubicaciones = []


opcion = ""

print("=== SISTEMA BÁSICO DE PARQUEADERO ===")

while opcion != "4":

    print("\nMapa del parqueadero:")
    for fila in mapa:
        print(" ".join(fila))


    print("\n1. Ingresar vehículo")
    print("2. Sacar vehículo")
    print("3. Ver disponibilidad")
    print("4. Salir")
    opcion = input("Elige una opción: ")

    if opcion == "1":
        placa = input("Ingresa la placa del vehículo: ").upper()

        if placa in placas:
            print("Ese vehículo ya está en el parqueadero.")
        else:
            encontrado = False
            for i in range(1, 7):
                for j in range(1, 8):
                    if mapa[i][j] == "L":
                        mapa[i][j] = "O"
                        placas.append(placa)
                        ubicaciones.append((i, j))
                        print("Vehículo registrado en posición:", i, j)
                        encontrado = True
                        break
                if encontrado:
                    break
            if not encontrado:
                print("No hay espacios disponibles.")

    elif opcion == "2":
        placa = input("Ingresa la placa del vehículo que va a salir: ").upper()

        if placa in placas:
            indice = placas.index(placa)
            ubicacion = ubicaciones[indice]
            i, j = ubicacion
            mapa[i][j] = "L"
            placas.pop(indice)
            ubicaciones.pop(indice)
            minutos = int(input("¿Cuántos minutos estuvo el vehículo?: "))
            tarifa = minutos * 100
            print("Vehículo retirado.")
            print("Valor a pagar: $", tarifa)
        else:
            print("Ese vehículo no está registrado.")

    elif opcion == "3":
        libres = 0
        ocupados = 0
        for i in range(1, 7):
            for j in range(1, 8):
                if mapa[i][j] == "L":
                    libres += 1
                elif mapa[i][j] == "O":
                    ocupados += 1
        print("Espacios libres:", libres)
        print("Espacios ocupados:", ocupados)

    elif opcion == "4":
        print("Gracias por usar el sistema.")
    else:
        print("Opción no válida.")